### PR TITLE
Fixes the centering issue

### PR DESCRIPTION
**Pull request by mortonjt**
This looks like it'll fix the centering issue.  Below is proof with the metabolomics data

image

We still need
- [x] unittests
- [ ] emperor mchelper with CF data

### CODE REVIEW

**Comment by cameronmartino** [comment]
@mortonjt looks like the test _expected_ output needs to be updated with the new centering for the standalone and q2 tests.

**Comment by mortonjt** [comment]
ok, @cameronmartino .  Fixed the standalone tests.  I'm at a bit of a loss on how to fix the q2 tests, thoughts?

**Comment by cameronmartino** [comment]
@mortonjt it seems to be passing. Not sure why 0e1b445 failed?

**Comment by mortonjt** [comment]
Maybe we don't need that assert statement anymore - I bet the sign issue is resolved with the SVD postprocessing step

**Comment by cameronmartino** [comment]
@mortonjt  agreed!

**Comment by mortonjt** [comment]
fyi - the percentages look a little weird.  otherwise, this should be good to go

**Comment by cameronmartino** [comment]
@mortonjt the percentages look okay too me? The centering is so much better (look at those metabolites)

#### microbes
emperor_microbes
#### metabolites
emperor_metabolites

**Comment by mortonjt** [comment]
Yeah, this looks reasonable to me

**Review by cameronmartino — APPROVED** [review]

**Pull request merged**
