### PR TITLE
Adding tests, documentation, arrow scaling issue

### PR DESCRIPTION
**Pull request by cameronmartino**
See changelog: TLDR:
* added tests 
* added comments and improved code readability
* fixed arrow scaling issue

### CODE REVIEW

**Comment by mortonjt** [comment]
Adding in PR from #38 to fix centering issue.

**Comment by cameronmartino** [comment]
fixes issue #37

**Comment by cameronmartino** [comment]
@mortonjt should be good to go. One last double check of the output from emperor. 

#### microbes
emperor_microbes

#### metabolites
emperor_metab

**Comment by mortonjt** [comment]
Cool. Let's get this merged in

**Pull request merged**
