### PR TITLE
Time to clean

### PR DESCRIPTION
**Pull request by cameronmartino**
* Updated rclr and inv. rclr to inductive architecture 
* Updated the optspace module to inductive architecture 
* Added testing for rclr/inv_rclr 
* Updated examples and benchmarking to new architecture 
* General code cleanup

TODO:

* docs
* either remove other methods or update to new architecture…

### CODE REVIEW

**Comment by mortonjt** [comment]
Looks like you forgot to include an init file.  You can just run

`touch __init__.py`

**Comment by cameronmartino** [comment]
> Looks like you forgot to include an init file. You can just run
> 
> `touch __init__.py`

There is definitely an init file in the deicode directory. I think maybe there something is going wrong with the change to lower case. 

pip install -e. is working fine locally as well

**Comment by mortonjt** [comment]
right - if you are going lowercase, you'll need to change that casing everywhere.  Including renaming all of your folders

**Comment by cameronmartino** [comment]
hmmm I see the dir. name is not converting to the lower case from the commits.

**Pull request merged**
